#! /usr/bin/env python3
import ply.lex as lex
import ply.yacc as yacc

# ---------------------------------
# TOKENS
# ---------------------------------
tokens = [
    'ID', 'ENTERO', 'FLOTANTE', 'CADENA',

    'PLUS', 'MINUS', 'STAR', 'SLASH', 'MOD',

    'LT', 'GT', 'LE', 'GE', 'EQ', 'NE', 'EQEQ',

    'LPARENTESIS', 'RPARENTESIS',
    'LLLAVE', 'RLLAVE',

    'PUNTOPUNTO', 'COMA',

    'NEWLINE', 'INDENT', 'DEDENT'
]

# ---------------------------------
# KEYWORDS
# ---------------------------------
keywords = {
    "int": "KW_INT",
    "float": "KW_FLOAT",
    "string": "KW_STRING",
    "bool": "KW_BOOL",
    "if": "KW_IF",
    "else": "KW_ELSE",
    "while": "KW_WHILE",
    "func": "KW_FUNC",
    "Read": "KW_READ",
    "Write": "KW_WRITE",
    "true": "BOOL",
    "false": "BOOL",
    "and": "AND",
    "or": "OR",
    "not": "NOT",
}

tokens += list(set(keywords.values()))


pila_indentacion = [0]
inicio_linea = True
linea_token = False
tabsize = 4
dedents_pendientes = []


t_PLUS = r'\+'
t_MINUS = r'-'
t_STAR = r'\*'
t_SLASH = r'/'
t_MOD = r'%'

t_EQEQ = r'=='
t_NE = r'!='
t_LE = r'<='
t_GE = r'>='
t_LT = r'<'
t_GT = r'>'
t_EQ = r'='

t_LPARENTESIS = r'\('
t_RPARENTESIS = r'\)'
t_LLLAVE = r'\{'
t_RLLAVE = r'\}'

t_PUNTOPUNTO = r':'
t_COMA = r','

t_ignore = ' \r'


def t_comment(t):
    r'\#.*'
    pass


def t_NEWLINE(t):
    r'\n+'
    global inicio_linea, linea_token
    t.lexer.lineno += len(t.value)

    if linea_token:
        linea_token = False
        inicio_linea = True
        return t

    inicio_linea = True


def t_INDENT(t):
    r'[ \t]+'
    global inicio_linea, dedents_pendientes

    if not inicio_linea:
        return

    col = 0
    for ch in t.value:
        if ch == ' ':
            col += 1
        else:
            col += tabsize - (col % tabsize)

    cima = pila_indentacion[-1]

    if col > cima:
        pila_indentacion.append(col)
        t.type = 'INDENT'
        inicio_linea = False
        return t

    elif col < cima:
        while len(pila_indentacion) > 1 and pila_indentacion[-1] > col:
            pila_indentacion.pop()
            dedents_pendientes.append('DEDENT')

        inicio_linea = False

        if dedents_pendientes:
            t.type = dedents_pendientes.pop(0)
            return t


def t_ID(t):
    r'[a-zA-Z_][a-zA-Z0-9_]*'
    global linea_token

    if len(t.value) > 31:
        print(f"Error: ID muy largo en linea {t.lexer.lineno}")
        t.value = t.value[:31]

    t.type = keywords.get(t.value, 'ID')
    linea_token = True
    return t


def t_FLOTANTE(t):
    r'\d+\.\d+'
    global linea_token
    linea_token = True
    return t

def t_ENTERO(t):
    r'\d+'
    global linea_token
    linea_token = True
    return t


def t_CADENA(t):
    r'"([^"\\]|\\.)*"'
    global linea_token
    linea_token = True
    return t


def t_error(t):
    print(f"Caracter ilegal '{t.value[0]}' en linea {t.lexer.lineno}")
    t.lexer.skip(1)

lexer = lex.lex()


precedence = (
    ('left', 'OR'),
    ('left', 'AND'),
    ('right', 'NOT'),
    ('nonassoc', 'LT', 'GT', 'LE', 'GE', 'EQEQ', 'NE'),
    ('left', 'PLUS', 'MINUS'),
    ('left', 'STAR', 'SLASH', 'MOD'),
)

def p_programa(p):
    'programa : sentencias'
    p[0] = ('programa', p[1])

def p_sentencias_multiple(p):
    'sentencias : sentencia sentencias'
    p[0] = [p[1]] + p[2]

def p_sentencias_unica(p):
    'sentencias : sentencia'
    p[0] = [p[1]]

def p_sentencia(p):
    '''sentencia : declaracion_variable
                 | asignacion
                 | sentencia_if
                 | sentencia_while
                 | entrada_salida'''
    p[0] = p[1]

def p_declaracion_variable(p):
    '''declaracion_variable : tipo ID
                            | tipo ID EQ expresion'''
    if len(p) == 3:
        p[0] = ('decl', p[1], p[2])
    else:
        p[0] = ('decl_assign', p[1], p[2], p[4])

def p_asignacion(p):
    'asignacion : ID EQ expresion'
    p[0] = ('assign', p[1], p[3])

def p_tipo(p):
    '''tipo : KW_INT
            | KW_FLOAT
            | KW_STRING
            | KW_BOOL'''
    p[0] = p[1]

# IF / ELSE
def p_if(p):
    '''sentencia_if : KW_IF expresion_booleana PUNTOPUNTO bloque
                    | KW_IF expresion_booleana PUNTOPUNTO bloque KW_ELSE PUNTOPUNTO bloque'''
    if len(p) == 5:
        p[0] = ('if', p[2], p[4], None)
    else:
        p[0] = ('if', p[2], p[4], p[7])

# WHILE
def p_while(p):
    'sentencia_while : KW_WHILE expresion_booleana PUNTOPUNTO bloque'
    p[0] = ('while', p[2], p[4])

# BLOQUE (INDENT)
def p_bloque(p):
    'bloque : NEWLINE INDENT sentencias DEDENT'
    p[0] = p[3]


def p_io(p):
    '''entrada_salida : KW_READ LPARENTESIS ID RPARENTESIS
                      | KW_WRITE LPARENTESIS expresion RPARENTESIS'''
    if p[1] == 'Read':
        p[0] = ('read', p[3])
    else:
        p[0] = ('write', p[3])


def p_bool_bin(p):
    '''expresion_booleana : expresion_booleana AND expresion_booleana
                          | expresion_booleana OR expresion_booleana'''
    p[0] = ('bool_op', p[2], p[1], p[3])

def p_bool_not(p):
    'expresion_booleana : NOT expresion_booleana'
    p[0] = ('not', p[2])

def p_bool_rel(p):
    'expresion_booleana : expresion operador_relacional expresion'
    p[0] = ('rel', p[2], p[1], p[3])

def p_bool_val(p):
    'expresion_booleana : BOOL'
    p[0] = ('bool', p[1])

def p_bool_paren(p):
    'expresion_booleana : LPARENTESIS expresion_booleana RPARENTESIS'
    p[0] = p[2]

def p_relop(p):
    '''operador_relacional : LT
                           | GT
                           | LE
                           | GE
                           | EQEQ
                           | NE'''
    p[0] = p[1]

# EXPRESIONES
def p_expr(p):
    '''expresion : expresion PLUS termino
                 | expresion MINUS termino'''
    p[0] = ('binop', p[2], p[1], p[3])

def p_expr_term(p):
    'expresion : termino'
    p[0] = p[1]

def p_term(p):
    '''termino : termino STAR factor
               | termino SLASH factor
               | termino MOD factor'''
    p[0] = ('binop', p[2], p[1], p[3])

def p_term_factor(p):
    'termino : factor'
    p[0] = p[1]

def p_factor(p):
    '''factor : ID
              | ENTERO
              | FLOTANTE
              | CADENA
              | BOOL
              | LPARENTESIS expresion RPARENTESIS'''
    if len(p) == 2:
        p[0] = ('val', p[1])
    else:
        p[0] = p[2]

# ERROR
def p_error(p):
    if p:
        print(f"Error sintactico en '{p.value}' linea {p.lineno}")
    else:
        print("Error sintactico al final")

parser = yacc.yacc()


if __name__ == "__main__":
    s = input("Ingrese cadena: ")
    resultado = parser.parse(s,lexer=lexer)
    print(resultado)

